# Updated configuration to use pandas for analytics
services:
  - type: web
    name: face-viewer-dashboard
    env: python
    runtime: python3.12.3
    buildCommand: "pip install --upgrade pip && pip install setuptools==69.0.3 && pip install wheel==0.42.0 && pip install meson-python==0.15.0 ninja==1.11.1 && pip install -r requirements.txt && pip install -r requirements-pandas.txt"
    startCommand: gunicorn wsgi:application
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DASHBOARD_SECRET_KEY
        generateValue: true
      - key: FERNET_KEY
        sync: false
      - key: FACE_VIEWER_DATA_DIR
        sync: false
      - key: FACE_VIEWER_BACKEND_URL
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: R_ENABLED
        value: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: "1"
    healthCheckPath: /
    autoDeploy: true
