services:
  - type: web
    name: face-viewer-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DASHBOARD_SECRET_KEY
        generateValue: true
      - key: FERNET_KEY
        sync: false
      - key: FACE_VIEWER_DATA_DIR
        sync: false
      - key: FACE_VIEWER_BACKEND_URL
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: R_ENABLED
        value: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
