# Minimal configuration without login requirements
services:
  - type: web
    name: face-viewer-dashboard
    env: python
    runtime: python3.12.3
    buildCommand: "pip install --upgrade pip && pip install flask gunicorn flask-cors"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DASHBOARD_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
