blank_issues_enabled: true
contact_links:
  - name: Face Viewer Dashboard Documentation
    url: https://github.com/VibeZero2/face-viewer-dashboard#readme
    about: Check the documentation before creating an issue
